name: flame_camera_tools
description: "Intuitive tools for creating immersive and dynamic camera behaviors in Flame-based games."
version: 3.0.0
repository: https://github.com/bszarlej/flame_camera_tools.git

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0

dev_dependencies:
  flutter_lints: ">=5.0.0 <7.0.0"
